project_id = "cbvipnqtfigvfmqotsaf"

[functions.ai-multi-rotation]
verify_jwt = false

[functions.ai-rotation]
verify_jwt = false

[functions.email-dispatcher]
verify_jwt = true

[functions.sms-dispatcher]
verify_jwt = true

[functions.whatsapp-dispatcher]
verify_jwt = true

[functions.create-campaign]
verify_jwt = true

[functions.dispatch-campaign]
verify_jwt = true

[functions.upload-audio-cloudinary]
verify_jwt = true

[functions.n8n-dispatcher]
verify_jwt = true
